name: DevSecOps CI Vulnerability Scan
on:
  push:
    branches: [ main ]
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t devsecops-scanner:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-scanner:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL, HIGH'

          # trigger scan